name: Update PDF_A profiles in veraPDF-library

on:
  push:
    branches:
      [ test_profiles ]
    paths:
      - 'PDF_A/**'
      - '!PDF_A/1a/**'
      - '!PDF_A/1b/**'
      - '!PDF_A/2a/**'
      - '!PDF_A/2b/**'
      - '!PDF_A/2u/**'
      - '!PDF_A/3a/**'
      - '!PDF_A/3b/**'
      - '!PDF_A/3u/**'
      - '!PDF_A/4/**'
      - '!PDF_A/4e/**'
      - '!PDF_A/4f/**'

jobs:
  update-files:
    if: github.repository == 'irinamavrina/veraPDF-validation-profiles'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Commit to veraPDF-library
        uses: drud/action-cross-commit@master
        with:
          source-folder: PDF_A
          destination-repository: https://irinamavrina:${{ secrets.FORK_TOKEN }}@github.com/irinamavrina/veraPDF-library
          destination-folder: core/src/main/resources/org/verapdf/pdfa/validation
          destination-branch: test_profiles
          git-user: "Git User"
          git-commit-message: ${{ github.event.head_commit.message }}
          git-commit-sign-off: "false"
          excludes: 1a:1b:2a:2b:2u:3a:3b:3u:4:4e:4f:PDFUA-1.xml:validationProfile.xsd
